### ISSUE TITLE
Startup errors with Wacom Intuos S

### ISSUE THREAD

**Issue by Garrom** [tb2097/wacom-gui#23]
Using Ubuntu 18.04 with XFce.
***
When tablet is not connected : 
`garrom@GarromMachine:~/Plocha/wacom-gui-0.3.0-rc1/wacom-gui$ python '/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py'
Traceback (most recent call last):
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py", line 429, in <module>
    main()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py", line 424, in main
    form = WacomGui()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py", line 62, in __init__
    self.refreshTablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py", line 88, in refreshTablets
    self.tablet_data.get_connected_tablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom_data.py", line 61, in get_connected_tablets
    self.__get_libwacom_data()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom_data.py", line 186, in __get_libwacom_data
    if data['pad']['buttons'].__len__() == 0:
KeyError: 'buttons'
`
***
After I connected tablet : 
`garrom@GarromMachine:~/Plocha/wacom-gui-0.3.0-rc1/wacom-gui$ python '/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py'
Traceback (most recent call last):
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom-gui.py", line 11, in <module>
    from wacom_data import Tablets
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom_data.py", line 390, in <module>
    tablet_test = Tablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom_data.py", line 32, in __init__
    self.get_connected_tablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc1/wacom-gui/wacom_data.py", line 68, in get_connected_tablets
    devID = self.device_data[dev_type]['devID']
KeyError: 'Wacom Intuos S Pad'
`
***
Is support for my tablet missing ?
 -Garrom

**Comment by tb2097** [comment]
I'm not sure why you would be getting an error when no device is connected; the code shouldn't be hitting that function without detecting "something".
Can you please provide the output for the command `libwacom-list-local-devices --database /usr/share/libwacom` when connect and disconnected?

**Comment by tb2097** [comment]
Are you trying to run it on an Thinkpad (ie. X1 Yoga) with an integrated touch display?  The input is detecting as a serial device, which I currently don't have any support for.  You should get getting output similar to below for your Intuos S tablet, when it is hooked up:
```
[Device]
Name=Wacom Intuos S
DeviceMatch=usb:056a:0374
Class=Bamboo
Width=8
Height=6
Layout=intuos-s-p3.svg
IntegratedIn=
Styli=0x862;

[Features]
Stylus=true
Reversible=false
Buttons=4

[Buttons]
Top=A;B;C;D
```

**Comment by tb2097** [comment]
I've released a new version that should remove any serial devices detected to hopefully allow your Intuos S to properly be detected and function in the GUI.  Please give it a try and let me know.

**Comment by Garrom** [comment]
> I've released a new version that should remove any serial devices detected to hopefully allow your Intuos S to properly be detected and function in the GUI. Please give it a try and let me know.

:disappointed: Why everyone's tablet works but mine.
```
garrom@GarromMachine:~/Plocha/wacom-gui-0.3.0-rc3/wacom-gui$ python '/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom-gui.py'
Traceback (most recent call last):
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom-gui.py", line 501, in <module>
    main()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom-gui.py", line 490, in main
    form = WacomGui()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom-gui.py", line 51, in __init__
    self.tablet_data = Tablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom_data.py", line 32, in __init__
    self.get_connected_tablets()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc3/wacom-gui/wacom_data.py", line 68, in get_connected_tablets
    devID = self.device_data[dev_type]['devID']
KeyError: 'Wacom Intuos S Pad'

```

**Comment by tb2097** [comment]
I'll do my best to get it working :)  As I only have Intuos 4/5/Pro and a couple Cintiqs to test with I'm bound to run into edge cases.  I've put in a fix which should resolve the issue.  Please test the latest release and let me know.

**Comment by Garrom** [comment]
> I'll do my best to get it working :) As I only have Intuos 4/5/Pro and a couple Cintiqs to test with I'm bound to run into edge cases. I've put in a fix which should resolve the issue. Please test the latest release and let me know.

I know what you mean. I'm game developer. Lack of hardware is biggest bane to debugging. They are like "Hey my 200$ Gpu does not work" and I'm like "and where the heck you think I can get your GPU ?"
```
garrom@GarromMachine:~/Plocha/wacom-gui-0.3.0-rc10/wacom-gui$ python '/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/wacom-gui.py'
Traceback (most recent call last):
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/wacom-gui.py", line 665, in <module>
    main()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/wacom-gui.py", line 654, in main
    form = WacomGui()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/wacom-gui.py", line 45, in __init__
    self.pad = Pad()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/pad.py", line 33, in __init__
    self.load_dconf()
  File "/home/garrom/Plocha/wacom-gui-0.3.0-rc10/wacom-gui/pad.py", line 56, in load_dconf
    with open(os.path.expanduser("~/.wacom-gui/custom.json"), 'r') as f:
IOError: [Errno 2] Adresář nebo soubor neexistuje: '/home/garrom/.wacom-gui/custom.json'
```
"Adresář nebo soubor neexistuje" means folder or file does not exist (My language is czech). Should I put something into /home/garrom/.wacom-gui ? There is no .wacom-gui in my home directory. Should I create .wacom-gui inside my home directory ? If it is part of installation process, it should be mentioned somewhere.

**Comment by tb2097** [comment]
That was a bug I missed due to not doing a clean install before testing :/  I've released a new version that should resolve that issue.

**Comment by tb2097** [comment]
update line 83 in pad.py:
`                    custom[new_entry] = {'name': "'%s'" % data['label'],`
`                    os_custom[new_entry] = {'name': "'%s'" % data['label'],`

I'll update the file in the repo when I'm on my dev machine.
