### ISSUE TITLE
wacom-gui dies on RHEL 7.6 with a Cintiq Pro 24 

### ISSUE THREAD

**Issue by montygreen** [tb2097/wacom-gui#26]
Manually starting wacom-gui produces the following errors:

[root@sulawesi ~]# wacom-gui
local variable 'svg_write' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 741, in <module>
    main()
  File "/usr/local/wacom-gui/wacom-gui.py", line 733, in main
    form = WacomGui()
  File "/usr/local/wacom-gui/wacom-gui.py", line 56, in __init__
    self.tablet_data = Tablets()
  File "/usr/local/wacom-gui/wacom_data.py", line 32, in __init__
    self.get_connected_tablets()
  File "/usr/local/wacom-gui/wacom_data.py", line 72, in get_connected_tablets
    devID = self.device_data[dev_type]['devID']
KeyError: 'Wacom Express Key Remote Pad'

[root@sulawesi ~]# xsetwacom list
Wacom Express Key Remote Pad pad	id: 14	type: PAD       
Wacom Cintiq Pro 24 Pen stylus  	id: 15	type: STYLUS    
Wacom Cintiq Pro 24 Pen eraser  	id: 17	type: ERASER    

[root@sulawesi ~]# journalctl -u wacom-gui
-- Logs begin at Wed 2019-01-30 17:17:27 PST, end at Tue 2019-02-05 13:10:12 PST. --
Feb 05 11:45:57 sulawesi systemd[1]: Started Load user settings for Wacom tablets.
Feb 05 11:48:15 sulawesi systemd[1]: Started Load user settings for Wacom tablets.
Feb 05 11:48:16 sulawesi runuser[112694]: pam_unix(runuser:session): session opened for user dj7 by (uid=0)
Feb 05 11:48:16 sulawesi python[112695]: detected unhandled Python exception in '/usr/local/wacom-gui/wacom-gui.py'
Feb 05 11:48:16 sulawesi python[112695]: can't communicate with ABRT daemon, is it running? [Errno 2] No such file or directory
Feb 05 11:48:16 sulawesi runuser[112694]: pam_unix(runuser:session): session closed for user dj7

**Comment by tb2097** [comment]
Can you please provide me the output from `libwacom-list-local-devices --database /usr/local/wacom-gui/data` ? I think this might be an issue of libwacom-data not having information for the Express Key Remote, similar to #25 having a naming issue.  If it is I'll submit a ticket for them to get it updated.

**Comment by tb2097** [comment]
Please try the latest release (https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc16), as the Cintiq Pro should still load, hopefully.

**Comment by montygreen** [comment]
I'll upgrade to rc16 to test but here's the database 

[root@sulawesi ~]# libwacom-list-local-devices --database /usr/local/wacom-gui/data
[Device]
Name=Wacom Cintiq Pro 24 P
DeviceMatch=usb:056a:037c;
Class=Cintiq
Width=20
Height=12
IntegratedIn=Display;
Styli=0x842;0x84a;0x160802;0x16080a;0x100802;0x10080a;0x140802;0x14080a;0x120802;0x100804;0x10080c;0x100902;0x10090a;0x80842;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
---------------------------------------------------------------
[Device]
Name=Wacom Cintiq Pro 24 P
DeviceMatch=usb:056a:037c;
Class=Cintiq
Width=20
Height=12
IntegratedIn=Display;
Styli=0x842;0x84a;0x160802;0x16080a;0x100802;0x10080a;0x140802;0x14080a;0x120802;0x100804;0x10080c;0x100902;0x10090a;0x80842;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
---------------------------------------------------------------
[Device]
Name=Wacom ExpressKey Remote
DeviceMatch=usb:056a:0331;
Class=Remote
Width=0
Height=0
IntegratedIn=
Layout=ek-remote.svg

[Features]
Reversible=false
Stylus=false
Ring=true
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=Ring;
NumStrips=0
Buttons=18
[Buttons]
Left=A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;
Right=
Top=
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=A;
Ring2=
EvdevCodes=0x100;0x101;0x102;0x103;0x104;0x105;0x106;0x107;0x108;0x109;0x130;0x131;0x132;0x133;0x134;0x135;0x126;0x127;
RingNumModes=3
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------

**Comment by montygreen** [comment]
With rc16 I get 2 popups on login:
1. Device information for "Wacom Express Key Remote" not found.
2. Device information for "Wacom Cintiq Pro 2 24" not found.

When I run wacom-gui manually, I got the same 2 popups and only after I dismissed them, did the script except out:
[root@sulawesi ~]# wacom-gui
local variable 'svg_write' referenced before assignment
local variable 'svg_write' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 741, in <module>
    main()
  File "/usr/local/wacom-gui/wacom-gui.py", line 733, in main
    form = WacomGui()
  File "/usr/local/wacom-gui/wacom-gui.py", line 70, in __init__
    self.refreshTablets()
  File "/usr/local/wacom-gui/wacom-gui.py", line 100, in refreshTablets
    self.tablet_data.get_connected_tablets()
  File "/usr/local/wacom-gui/wacom_data.py", line 63, in get_connected_tablets
    self.__get_libwacom_data()
  File "/usr/local/wacom-gui/wacom_data.py", line 194, in __get_libwacom_data
    if data['pad']['buttons'].__len__() == 0:
KeyError: 'buttons'

**Comment by tb2097** [comment]
Hacks put in place to hopefully fix detection for Cintiq Pro 24 & ExpressKeys. (https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc17).  If the hacks work I'll contact libwacom-data to update their config files.

**Comment by tb2097** [comment]
Please try using the latest release: https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc18, let me know if this resolves the issue.
