### ISSUE TITLE
Device information not found

### ISSUE THREAD

**Issue by justinclift** [tb2097/wacom-gui#29]
Plugged in my old Wacom tablet, an Intuos "pen & touch small" (CTH-480) as I need to do some graphics stuff over the next few days.

Trying out Wacom GUI (wacom-gui v0.3.0-rc17 rpm download) just displays a error box twice:

![Wacom_GUI-screenshot1](https://user-images.githubusercontent.com/406299/54897036-e4ed1f00-4f1a-11e9-804c-be8c995e91ef.png)

... then a mostly blank window:

![Wacom_GUI-screenshot2](https://user-images.githubusercontent.com/406299/54897045-ec142d00-4f1a-11e9-9d4a-fc031695141b.png)

The console output (as this was launched manually from the cli) shows:

```
$ /usr/local/bin/wacom-gui
invalid literal for float(): 2,10.5
invalid literal for float(): 2,10.5
```

The problem sounds a lot like what's described in a comment on https://github.com/tb2097/wacom-gui/issues/26#issuecomment-461136753.

For reference:

```
$ xsetwacom list
Wacom Intuos PT S Pad pad               id: 9   type: PAD       
Wacom Intuos PT S Pen stylus            id: 10  type: STYLUS    
Wacom Intuos PT S Pen eraser            id: 11  type: ERASER    
Wacom Intuos PT S Finger touch          id: 12  type: TOUCH
```

```
$ libwacom-list-local-devices --database /usr/local/wacom-gui/data
[Device]
Name=Intuos Pen & Touch Small
DeviceMatch=usb:056a:0302;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-pt.svg
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=true
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
[Device]
Name=Intuos Pen & Touch Small
DeviceMatch=usb:056a:0302;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-pt.svg
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=true
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
[Device]
Name=Intuos Pen & Touch Small
DeviceMatch=usb:056a:0302;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-pt.svg
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=true
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```

**Comment by justinclift** [comment]
Note that getting Wacom GUI working isn't critical to me.  Just tried it more from curiosity than anything else.  I was able to switch the table to Relative mode (instead of the default Absolute) using xsetwacom, which should be "good enough" for the task at hand. :smile:

    xsetwacom --set "Wacom Intuos PT S Pen stylus" mode Relative

**Comment by tb2097** [comment]
If you update the file `/usr/local/wacom-gui/data/intuos-s-pt.tablet`, you should be able to make it work.
```
- Name=Intuos Pen & Touch Small
+ Name=Wacom Intuos PT S```

If that works, I can just submit another support ticket for libwacom :)

**Comment by justinclift** [comment]
Interesting.  That does help, as the two warning dialogs no longer appear, and some of the graphics appear to load. :smile:

![Wacom_GUI-screenshot3](https://user-images.githubusercontent.com/406299/54957971-6048e200-4fa8-11e9-97fb-29f7fdb009e1.png)
![Wacom_GUI-screenshot4](https://user-images.githubusercontent.com/406299/54957972-6048e200-4fa8-11e9-8e5d-acea29241d3d.png)

It doesn't look 100% correct though, as some errors are displayed on the console (launching this via CLI) as I click on the various buttons.  eg `Functions`, `Stylus`, `Touch`:

```
 wacom-gui 
invalid literal for float(): 2,10.5
invalid literal for float(): 2,10.5
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 298, in tabletSelect
    self.updateConfigs()
  File "/usr/local/wacom-gui/wacom-gui.py", line 367, in updateConfigs
    if pad != self.configs[self.dev][self.config]['pad']['buttons']:
KeyError: None
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 338, in configSelect
    self.loadConfig(self.dev, self.dev_id, config)
  File "/usr/local/wacom-gui/wacom-gui.py", line 278, in loadConfig
    self.configs[dev][config]['pad']['buttons'])
KeyError: 'default'
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 338, in configSelect
    self.loadConfig(self.dev, self.dev_id, config)
  File "/usr/local/wacom-gui/wacom-gui.py", line 278, in loadConfig
    self.configs[dev][config]['pad']['buttons'])
KeyError: 'default'
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 298, in tabletSelect
    self.updateConfigs()
  File "/usr/local/wacom-gui/wacom-gui.py", line 367, in updateConfigs
    if pad != self.configs[self.dev][self.config]['pad']['buttons']:
KeyError: 'default'
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 437, in closeEvent
    self.updateConfigs()
  File "/usr/local/wacom-gui/wacom-gui.py", line 367, in updateConfigs
    if pad != self.configs[self.dev][self.config]['pad']['buttons']:
KeyError: 'default'
$
```

**Comment by tb2097** [comment]
This appears to be an issue with parsing out the SVG file for the tablet; when I get a moment I'll try and discern if it's an issue with the script or the format of the SVG itself.

**Comment by justinclift** [comment]
No worries @tb2097. :smile:

**Comment by tb2097** [comment]
Please try using the latest release: https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc18, let me know if this resolves the issue.
