### ISSUE TITLE
device information for "wacom intuos BT M" not found

### ISSUE THREAD

**Issue by fidave** [tb2097/wacom-gui#32]
```
$ python wacom-gui.py 
invalid literal for float(): 42,10.5
invalid literal for float(): 42,10.5
Traceback (most recent call last):
  File "wacom-gui.py", line 741, in <module>
    main()
  File "wacom-gui.py", line 733, in main
    form = WacomGui()
  File "wacom-gui.py", line 70, in __init__
    self.refreshTablets()
  File "wacom-gui.py", line 100, in refreshTablets
    self.tablet_data.get_connected_tablets()
  File "/home/super/ws/wacom/wacom-gui-0.3.0-rc16/wacom-gui/wacom_data.py", line 63, in get_connected_tablets
    self.__get_libwacom_data()
  File "/home/super/ws/wacom/wacom-gui-0.3.0-rc16/wacom-gui/wacom_data.py", line 194, in __get_libwacom_data
    if data['pad']['buttons'].__len__() == 0:
KeyError: 'buttons'

```

```
$ xsetwacom --list devices
Wacom Intuos BT M Pen stylus    	id: 14	type: STYLUS    
Wacom Intuos BT M Pen eraser    	id: 15	type: ERASER    
Wacom Intuos BT M Pen cursor    	id: 16	type: CURSOR    
Wacom Intuos BT M Pad pad       	id: 17	type: PAD 
```

```
$ libwacom-list-local-devices
# Device node: /dev/input/event16
[Device]
Name=Wacom Intuos BT M
ModelName=CTL-6100WL
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=10
Height=8
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event15
[Device]
Name=Wacom Intuos BT M
ModelName=CTL-6100WL
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=10
Height=8
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```

**Comment by tb2097** [comment]
Can you please try with RC17?  I believe there was an issue with RC16 that I had missed in the dev process, hence it being removed from the release list.

**Comment by fidave** [comment]
thanks @tb2097 , I tried rc17, no exception but still got`device information for "wacom intuos BT M" not found`
```
$ python wacom-gui.py 
invalid literal for float(): 42,10.5
invalid literal for float(): 42,10.5
```

**Comment by pascaldulieu** [comment]
I'm getting the exact same errors with the `Wacom Intuos S` only difference is that mine will throw 
```
invalid literal for float(): 2,10.5
invalid literal for float(): 2,10.5
```

**Comment by tb2097** [comment]
I unfortunately don't have any of these tablets to test out, but I was able to identify _where_ the error is coming from.  The errors are occurring due to the SVG file for the tablet failing to parse out correctly, as they use a different format from the tablets I have worked with.  I'll have to add in an additional parsing pass for buttons that don't use circles/squares.  I'll try to get to this in a week or two when (hopefully) I have some free time.

**Comment by tb2097** [comment]
I have updated the file [wacom_data.py](https://github.com/tb2097/wacom-gui/blob/master/wacom-gui/wacom_data.py) can you please try replacing the one in your current release and let me know if it resolves the error?  As well, let me know if a file `/tmp/intuos-m-p3.svg` exists or not if it does still crash.

**Comment by ochoadavid** [comment]
Sorry to bug this closed bug...

I'm still having this problem. I think it happens when parsing the original svg file (one in /usr/share). 
The problematic line is this:
`    <path id="ButtonA" class="A Button" d="M 42,10.5 a 12.75,8.5 0 0 1 12.75,-8.5 l 23.75,0 l 0,19 l -23.75,0 a 12.75,8.5 0 0 1 -12.75,-8.5 l 0,-2"/>
`

Hope it helps
David

**Comment by tb2097** [comment]
Please try using the latest release: https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc18, let me know if this resolves the issue.
