### ISSUE TITLE
Error at startup with Wacom Intuos BT M - Ubuntu 19.04

### ISSUE THREAD

**Issue by Sominemo** [tb2097/wacom-gui#33]
```
invalid literal for float(): 42,10.5
invalid literal for float(): 42,10.5
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 741, in <module>
    main()
  File "/usr/local/wacom-gui/wacom-gui.py", line 733, in main
    form = WacomGui()
  File "/usr/local/wacom-gui/wacom-gui.py", line 70, in __init__
    self.refreshTablets()
  File "/usr/local/wacom-gui/wacom-gui.py", line 108, in refreshTablets
    self.tabletSelect(0)
  File "/usr/local/wacom-gui/wacom-gui.py", line 299, in tabletSelect
    self.setToolsAvail(idx)
  File "/usr/local/wacom-gui/wacom-gui.py", line 134, in setToolsAvail
    self.tablet_data.tablets[self.dev][self.dev_id]['eraser']['id']]
KeyError: 'eraser'
```

**Comment by tb2097** [comment]
same issue as #32; closing duplicate ticket.
