### ISSUE TITLE
Crash with Intuos PT 2 CTH-690

### ISSUE THREAD

**Issue by Acidpix** [tb2097/wacom-gui#49]
Hi i have somme issue with wacom-gui 
i try with rc17 and rc18. i'm on Centos 7.7
Out of box i have this error : Device information for "Wacom Intuos PT M 2" not found
But im go to data folder and change name in intuos-m-pt2.tablet to Wacom Intuos PT M 2
Buit when i try to lunch i have this error : 

> Qt: Session management error: None of the authentication protocols specified are supported
> error: The connection is closed
> 
> Usage:
>   dconf load DIR 
> 
> Populate a subpath from stdin
> 
> Arguments:
>   DIR         A directory path (starting and ending with '/')
> 
> 
> invalid literal for float(): 13.0,25.25
> invalid literal for float(): 13.0,25.25
> Traceback (most recent call last):
>   File "wacom-gui.py", line 746, in <module>
>     main()
>   File "wacom-gui.py", line 738, in main
>     form = WacomGui()
>   File "wacom-gui.py", line 70, in __init__
>     self.refreshTablets()
>   File "wacom-gui.py", line 113, in refreshTablets
>     self.tabletSelect(0)
>   File "wacom-gui.py", line 304, in tabletSelect
>     self.setToolsAvail(idx)
>   File "wacom-gui.py", line 139, in setToolsAvail
>     self.tablet_data.tablets[self.dev][self.dev_id]['eraser']['id']]
> KeyError: 'eraser'

my xsetwacom list : 

> Wacom Intuos PT M 2 Pad pad     	id: 12	type: PAD       
> Wacom Intuos PT M 2 Pen stylus  	id: 13	type: STYLUS    
> Wacom Intuos PT M 2 Finger touch	id: 14	type: TOUCH 

my libwacom-list-local-devices :

> [Device]
> Name=Intuos Pen & Touch Medium
> DeviceMatch=usb:056a:033e;
> Class=Bamboo
> Width=9
> Height=5
> IntegratedIn=
> Layout=intuos-m-pt2.svg
> Styli=0x8e2;
> 
> [Features]
> Reversible=false
> Stylus=true
> Ring=false
> Ring2=false
> Touch=true
> TouchSwitch=true
> StatusLEDs=
> NumStrips=0
> Buttons=4
> [Buttons]
> Left=
> Right=
> Top=A;B;C;D;
> Bottom=
> Touchstrip=
> Touchstrip2=
> OLEDs=
> Ring=
> Ring2=
> EvdevCodes=0x110;0x111;0x115;0x116;
> RingNumModes=0
> Ring2NumModes=0
> StripsNumModes=0
> 
> ---------------------------------------------------------------
> [Device]
> Name=Intuos Pen & Touch Medium
> DeviceMatch=usb:056a:033e;
> Class=Bamboo
> Width=9
> Height=5
> IntegratedIn=
> Layout=intuos-m-pt2.svg
> Styli=0x8e2;
> 
> [Features]
> Reversible=false
> Stylus=true
> Ring=false
> Ring2=false
> Touch=true
> TouchSwitch=true
> StatusLEDs=
> NumStrips=0
> Buttons=4
> [Buttons]
> Left=
> Right=
> Top=A;B;C;D;
> Bottom=
> Touchstrip=
> Touchstrip2=
> OLEDs=
> Ring=
> Ring2=
> EvdevCodes=0x110;0x111;0x115;0x116;
> RingNumModes=0
> Ring2NumModes=0
> StripsNumModes=0
> 
> ---------------------------------------------------------------
> [Device]
> Name=Intuos Pen & Touch Medium
> DeviceMatch=usb:056a:033e;
> Class=Bamboo
> Width=9
> Height=5
> IntegratedIn=
> Layout=intuos-m-pt2.svg
> Styli=0x8e2;
> 
> [Features]
> Reversible=false
> Stylus=true
> Ring=false
> Ring2=false
> Touch=true
> TouchSwitch=true
> StatusLEDs=
> NumStrips=0
> Buttons=4
> [Buttons]
> Left=
> Right=
> Top=A;B;C;D;
> Bottom=
> Touchstrip=
> Touchstrip2=
> OLEDs=
> Ring=
> Ring2=
> EvdevCodes=0x110;0x111;0x115;0x116;
> RingNumModes=0
> Ring2NumModes=0
> StripsNumModes=0
> 
> ---------------------------------------------------------

**Comment by tb2097** [comment]
This is particular to that tablet, I wasn't aware there were pens without erasers (assumption on my part).  I'll have to look into this further, but it should be possible to fix.
